language: go
go:
- 1.7
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get -t -v ./...
script:
- go build
# - go test -v -race -covermode=count -coverprofile=coverage.out
# - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
notifications:
  email: false
